services:
  - type: web
    name: stock-price-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    runtime: python
    pythonVersion: 3.10.13
